### ISSUE TITLE
Premiumvanish support & lp 

### ISSUE THREAD

**Issue by TymonLC** [MrIvek/OnlineGUI#2]
Hi, i have 2 suggestions
Luckpemrs prefix (instead Ex. Operator) [Owner] nick
2. Vanish support (premiumvanish & super vanish - free api which working in both plugins is on SuperVabish page)

I hope you can do it!! If Yes this will be THE BEST ONLINEGUI PLUGIN!!!!!!!

**Comment by MrIvek** [comment]
Hi @TymonLC ,

do u use [LPC - Chat Formatter](https://www.spigotmc.org/resources/lpc-chat-formatter-1-7-10-1-20.68965/)?

**Comment by MrIvek** [comment]
Added support for LuckPerms on new version [1.10.1](https://www.spigotmc.org/resources/onlinegui.82988/)
